---
- name: create a disk
  gcp_compute_disk:
    name: 'disk-instance'
    size_gb: 50
    source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts'
    zone: us-central1-a
    project: on-demand-runners
    auth_kind: serviceaccount
    service_account_file: "/home/circleci/gcloud-service-key.json"
    # service_account_file: "/Users/derry/projects/personal/derry-on-demand-runner/auto-runner/vars/on-demand-runners-3c9a2f7eb6e8.json"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
  register: disk
- name: create a address
  gcp_compute_address:
    name: 'address-instance'
    region: us-central1
    project: on-demand-runners
    auth_kind: serviceaccount
    service_account_file: "/home/circleci/gcloud-service-key.json"
    # service_account_file: "/Users/derry/projects/personal/derry-on-demand-runner/auto-runner/vars/on-demand-runners-3c9a2f7eb6e8.json"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
  register: address
- name: create a instance
  gcp_compute_instance:
    state: present
    name: test-vm
    machine_type: n1-standard-1
    disks:
      - auto_delete: true
        boot: true
        source: "{{ disk }}"
    network_interfaces:
        - network: null # use default
          access_configs:
            - name: 'External NAT'
              nat_ip: "{{ address }}"
              type: 'ONE_TO_ONE_NAT'
    zone: us-central1-a
    project: on-demand-runners
    auth_kind: serviceaccount
    service_account_file: "/home/circleci/gcloud-service-key.json"
    # service_account_file: "/Users/derry/projects/personal/derry-on-demand-runner/auto-runner/vars/on-demand-runners-3c9a2f7eb6e8.json"
    scopes:
      - https://www.googleapis.com/auth/compute
  register: instance

- name: Wait for SSH to come up
  wait_for: host={{ address.address }} port=22 delay=10 timeout=180

- name: Add host to groupname
  add_host: hostname={{ address.address }} groupname=new_instances

- name: Template Compute Dynamic Inventory to only target On Demand Runners
  template:
    src: "compute.gcp.yml.j2"
    dest: "compute_gcp.yml"

- name: Manage new instances
  hosts: new_instances
  connection: ssh
  become: True
