---
- name: create a instance
  vars:
    gcp_cred_file: "{{ GCLOUD_SERVICE_KEY }}"
  gcp_compute_instance:
    state: present
    name: test-vm
    machine_type: n1-standard-1
    disks:
      - auto_delete: true
        boot: true
        source: "{{ disk }}"
    network_interfaces:
        - network: null # use default
          access_configs:
            - name: 'External NAT'
              nat_ip: "{{ address }}"
              type: 'ONE_TO_ONE_NAT'
    zone: us-central1-a
    project: on-demand-runners
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
  register: instance

- name: Wait for SSH to come up
  wait_for: host={{ address.address }} port=22 delay=10 timeout=60

- name: Add host to groupname
  add_host: hostname={{ address.address }} groupname=new_instances